version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  events-web:
    depends_on:
      - rabbitmq
    image: distilledsch/dsch-events:0.1.48
    ports:
    - 8080:8080
    environment:
      DSCH_EVENTS_SERVER_HOSTNAME: rabbitmq
  config:
    depends_on:
      - rabbitmq
    build: docker/
    restart: "no"
    volumes:
      - ./docker/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./docker/bootstrap.sh:/bootstrap.sh
    environment:
      RABBIT_HOST: rabbitmq